krazemon/repcoin

api/handlers/user.js
api/models/User.js
api/routes/UserRoutes.js
js/components/Signup.jsx
package.json
scripts/mockUserData.json

Remove phone number

---

css/app.css
js/components/Modal.jsx

Add message for no possible investments

---

css/app.css
js/components/CategoriesHeader.jsx
js/components/CategoriesTable.jsx
js/components/PortfolioTable.jsx

Add empty table message

---

api/handlers/user.js
api/models/VerificationToken.js
api/routes/UserRoutes.js
js/components/VerificationPage.jsx
spec/user_handler_spec.js

Save verification token and mark as triggered

---

css/app.css
js/components/AboutBox.jsx
js/components/SuperScore.jsx
js/components/SuperScoreInput.jsx

Defaultcategories

---

js/components/LinkInput.jsx
js/components/LinkItem.jsx
js/components/LinksBox.jsx
js/components/ProfileBox.jsx

Add text for no content

---

api/routes/UserRoutes.js

Increase reps count and investors count for new investor

---

api/handlers/user.js
api/models/Category.js
api/models/User.js
api/routes/TransactionRoutes.js
scripts/mockCategoryData.json
spec/user_handler_spec.js

Decrement users

---

css/app.css
js/components/Feed.jsx
package.json

Feed message and fix obscure error

---

api/routes/TransactionRoutes.js
api/routes/utils.js
spec/routes_utils_spec.js

Fix valuation error

---

config/pass.js

Fix email problem

---

js/components/LeaderTable.jsx

Fix leader table for investors

---

api/handlers/user.js
js/components/ProfileBox.jsx
js/components/SearchPageUser.jsx
scripts/mockUserData.json

Fixes #406
This just takes away the ability to add a defaultCategory, and it does not show the default category anywhere. It does not actually remove the field from mongo or remove the SuperScore code

Remove defaultCategory

---

api/models/User.js
js/components/PictureBox.jsx
js/components/PictureUploadModal.jsx
js/components/SearchPageUser.jsx
js/components/Signup.jsx

Scrape facebook profile picture

---

css/app.css
js/components/CategoriesPage.jsx
js/components/Feed.jsx
js/components/FeedHeader.jsx
js/components/PortfolioHeader.jsx
js/components/PortfolioTable.jsx
js/components/ProfilePage.jsx

Fixes #416 
Fixes #415 
Fixes #412

Minor frontend changes

---

js/components/Login.jsx

Reset password field after attempted login

---

css/app.css
js/components/CategoriesTable.jsx
js/components/CategoryInput.jsx
js/components/PortfolioTable.jsx

Add categories

---

api/routes/AuthRoutes.js
config/pass.js
js/auth.jsx
js/components/Login.jsx
package.json

Revert "Login component now displays correct msg"

---

api/routes/AuthRoutes.js
config/pass.js
js/auth.jsx
js/components/Login.jsx
package.json

"Login component now displays correct msg""

---

js/app.jsx
js/auth.jsx
js/components/AboutInput.jsx
js/components/CategoriesTable.jsx
js/components/CategoryInput.jsx
js/components/CategoryPageHeader.jsx
js/components/Footer.jsx
js/components/LinkInput.jsx
js/components/LinkItem.jsx
js/components/Login.jsx
js/components/Modal.jsx
js/components/PasswordResetPage.jsx
js/components/PictureUploadModal.jsx
js/components/PortfolioTable.jsx
js/components/Signup.jsx
js/components/SuperScoreInput.jsx
js/components/Toolbar.jsx
js/components/VerificationPage.jsx
js/mixins/AuthenticatedRoute.jsx
js/mixins/LoggedInRoute.jsx

Remove frontend authentication

---

js/components/CategoryInput.jsx
js/components/InstantBox.jsx

Search bar

---

js/components/CategoriesTable.jsx
js/components/LoginPage.jsx
js/components/PortfolioItem.jsx
js/components/PortfolioTable.jsx
js/components/ProfilePage.jsx

Fixes #446 
Fixes #443 
Fixes #439
Fixes #437

Fix bugs and publicize investor categories

---

js/components/AboutBox.jsx
js/components/CategoriesTable.jsx
js/components/LinkItem.jsx
js/components/LinksBox.jsx
js/components/LoginPage.jsx
js/components/PortfolioItem.jsx
js/components/PortfolioTable.jsx
js/components/ProfilePage.jsx

Fixes #451
Please look at other PR first, this one builds on that

Reset state

---

js/app.jsx
js/components/CategoryInput.jsx
js/components/CategorySearch.jsx
js/components/CategorySearchDisplayTable.jsx
js/components/InstantBox.jsx
js/components/SearchBar.jsx
js/components/SearchDisplayTable.jsx

Hide search results when click off

---

js/auth.jsx
js/mixins/AuthenticatedRoute.jsx

Make AuthenticatedRoute mixin work after server restart

---

api/routes/utils.js
js/components/Modal.jsx
spec/routes_utils_spec.js

Prevent transactions with 0 reps

---

api/models/User.js

Remember to run ```db.users.dropIndexes()``` on PROD.

Users can revoke all transactions

---

js/components/AboutInput.jsx

Use existing about text on update

---

api/routes/UserRoutes.js
js/components/CategoryInput.jsx

Fix message for already investor or expert

---

api/models/User.js
api/routes/TransactionRoutes.js
api/routes/utils.js
js/components/InvestmentItem.jsx
js/components/Modal.jsx
js/components/PortfolioTable.jsx
scripts/mockUserData.json
spec/routes_utils_spec.js

Revert "Dividends"

---

api/routes/TransactionRoutes.js
api/routes/utils.js
spec/routes_utils_spec.js

Remove investor if revoking last investment

---

api/models/User.js
api/routes/TransactionRoutes.js
api/routes/utils.js
js/components/InvestmentItem.jsx
js/components/Modal.jsx
js/components/PortfolioTable.jsx
scripts/mockUserData.json
spec/routes_utils_spec.js

This reverts commit 07ea1307bfd1a17f2228760a5a7bf00b1071f8f0.
Conflicts:
api/routes/utils.js
spec/routes_utils_spec.js

Revert "Revert "Dividends""

---

package.json
server.js

Fixes #477 
Decision based on information gleamed from [this](http://stackoverflow.com/questions/8749907/what-is-a-good-session-store-for-a-single-host-node-js-production-app) post.

Use production-compatible session store

---

js/components/Signup.jsx

Do not reset picture for returning users

---

js/components/ProfilePage.jsx

Change profile page layout

---

css/app.css
js/components/HomePage.jsx
js/components/ProfileQuickView.jsx

Create quick view card for profile viewing on home page

---

index.html

Add metadata for google search

---

api/routes/utils.js
js/components/Modal.jsx
spec/routes_utils_spec.js

Make it possible to donate in hundredths

---

api/models/User.js
bin/utils.js
spec/jobs_utils_spec.js

Round to nearest hundredth

---

js/components/InvestmentButton.jsx
js/components/ProfileBox.jsx
js/components/ProfilePage.jsx

Move investment button

---

css/app.css
js/components/SearchDisplayTable.jsx
js/components/SearchItem.jsx

Fixes #500
I encourage you to check the link to the default category image. It's up for debate

Differentiate users and categories

---

js/components/Modal.jsx

Quick and easy solution to make the amount message way less confusing

Change amount message

---

css/app.css
js/components/CategorySearchDisplayTable.jsx
js/components/SearchDisplayTable.jsx
js/components/SearchItem.jsx

- Categories will now also come up as blue in the search bar
- Fixed a bug where search in the categories table wasn't working
Fixes #500 #501

Add color for categories search item and fix bug

---

api/routes/UserRoutes.js
css/app.css
js/components/BecomeInvestorPrompt.jsx
js/components/Modal.jsx

Allow users to add categories from modal

---

css/app.css
js/components/Modal.jsx

Add modal messages

---

css/app.css
js/components/Feed.jsx
js/components/FeedItem.jsx
js/components/ProfileQuickView.jsx

Add basic pagination

---

css/app.css
js/components/Modal.jsx

Add no investments to revoke message to modal

---

api/routes/CategoryRoutes.js
css/app.css
js/components/CategoriesList.jsx
js/components/CategoriesPage.jsx
js/components/CategoriesPageFilter.jsx
js/components/Category.jsx

Add sorting for category page

---

js/components/InvestmentItem.jsx
js/components/InvestmentList.jsx

Hyperlink investment names and fix flatten children

---

css/app.css
js/components/FeedItem.jsx
js/lib/strings_utils.js

Add feed images and string lib

---

js/components/CategoriesItem.jsx
js/components/CategoriesTable.jsx
js/components/InvestorList.jsx
js/components/ProfileQuickView.jsx

Fix invariant violation

---

js/components/ContactUsPage.jsx

Include link to google forum on signup page

---

api/handlers/notification.js
api/handlers/user.js
api/models/Notification.js
api/routes/NotificationRoutes.js
api/routes/TransactionRoutes.js
api/routes/UserRoutes.js
config/pass.js
css/app.css
js/components/NotificationDisplay.jsx
js/components/Toolbar.jsx
scripts/populateTestDB.sh
server.js
spec/notification_handler_spec.js
spec/user_handler_spec.js

Notifications

---

config/pass.js

Add event for joining on facebook

---

js/components/Modal.jsx

Do not allow negative amounts

---

api/handlers/combo.js
api/handlers/notification.js
api/handlers/user.js
api/routes/AuthRoutes.js
api/routes/CategoryRoutes.js
api/routes/ComboRoutes.js
api/routes/TransactionRoutes.js
api/routes/UploadRoutes.js
api/routes/UserRoutes.js

Winston has way too many messages

Remove winston unnecessary logging

---

css/app.css
js/components/EventFeedItem.jsx

Add pictures to join event

---

api/handlers/transaction.js
api/models/User.js
js/components/Modal.jsx
js/components/PortfolioHeader.jsx
js/components/PortfolioTable.jsx
js/components/ProfileQuickView.jsx
scripts/destoryTestDB.sh
scripts/populateTestDB.sh

Fixes #556
Fixes #555
Fixes #554 
Fixes #553
Fixes #552
Fixes #550

Fix many bugs

---

api/handlers/user.js
api/routes/utils.js
spec/routes_utils_spec.js
spec/user_handler_spec.js

Update percentiles on category delete

---

css/app.css
js/components/CategoryPageHeader.jsx

Fix btn error and background color

---

css/app.css
js/components/Feed.jsx
js/components/FeedHeader.jsx
js/components/InvestmentButton.jsx
js/components/LinksBox.jsx
js/components/Modal.jsx
js/components/PortfolioHeader.jsx
js/components/PortfolioTable.jsx
js/components/ProfileBox.jsx
js/lib/strings_utils.js

Add tooltips

---

api/routes/CategoryRoutes.js
api/routes/UserRoutes.js
config/censor.js
config/naughtylist.js
js/components/CategoriesTable.jsx
js/components/CategoryInput.jsx
js/components/PortfolioTable.jsx
js/lib/strings_utils.js
server.js

Fixes #565
Not a comprehensive list or complete strategy but a good start

Build naughty list middleware

---

css/app.css
js/components/CategoryPage.jsx
js/components/ErrorPage.jsx
js/mixins/LoggedInRoute.jsx

Show error message when they go to non-existent category page

---

api/handlers/user.js
api/models/User.js
api/routes/utils.js
css/app.css
js/components/LocationBox.jsx
js/components/LocationInput.jsx
js/components/ProfileBox.jsx
js/lib/strings_utils.js

Add location to user model

---

config/censor.js

Fix naughty list

---

config/censor.js
js/components/FeedHeader.jsx

Feed buttons

---

config/censor.js
css/app.css

Background

---

css/app.css
js/components/BecomeInvestorPrompt.jsx

Fix spacing for investor prompt buttons

---

js/components/CategoriesPage.jsx
js/components/CategoriesPageFilter.jsx
js/lib/strings_utils.js

Add new filters and fix filter

---

api/models/Notification.js
api/routes/UserRoutes.js
api/routes/utils.js
config/acl.js
config/mailer.js
js/app.jsx
js/components/CategoryInput.jsx
js/components/CategoryRequestPage.jsx
js/lib/strings_utils.js
spec/routes_utils_spec.js

Fixes #577
Lemme merge because we need a new env variable

Category moderation

---

js/components/Modal.jsx

Reset modal state on profile change

---

api/routes/AuthRoutes.js
api/routes/UserRoutes.js
config/acl.js
config/pass.js
js/components/Login.jsx
js/components/LoginPage.jsx
server.js

Lock down site for beta

---

api/routes/utils.js

Round off investment amounts

---

bin/utils.js
js/components/Modal.jsx

Reps value is not enforced for give

---

api/routes/utils.js

Fix urls in category request email

---

js/components/LinkItem.jsx

Link to full urls for content links

---

js/components/InstantBox.jsx
js/components/SearchDisplayTable.jsx

Taper search results

---

api/handlers/user.js
api/routes/UserRoutes.js

Move join event until after verification

---

js/components/LinkItem.jsx

Fix HTTPs bug

---

js/components/CategoryInput.jsx
js/mixins/InputMixin.jsx

Validate Category Inputs

---

server.js

Fix Image Size upload issues

---

api/handlers/combo.js
api/models/AddExpertEvent.js
api/routes/UserRoutes.js
api/routes/utils.js
js/components/AddExpertEventFeedItem.jsx
js/components/Feed.jsx
spec/combo_handler_spec.js

Create event for becoming an expert

---

api/handlers/transaction.js
api/routes/utils.js
spec/routes_utils_spec.js

Fix full revoke bug

---

api/handlers/user.js
api/models/User.js
api/routes/UserRoutes.js
api/routes/utils.js
js/components/LeaderTable.jsx
spec/user_handler_spec.js

Fix all time leaders

---

js/components/InvestmentItem.jsx

Add percent return

---

index.ejs

Fix dead links

---

api/handlers/user.js
api/models/Transaction.js

Leading should only have active experts

---

api/routes/utils.js
bin/recountCategoryInvestorExpertsAndReps.js
bin/removeInvestorsWithNoInvestments.js
bin/utils.js
spec/jobs_utils_spec.js

Fixes #684
Fixes #685 
Do not run migration yet.

Fix empty investors and recount categories

---

api/routes/UserRoutes.js
js/components/PasswordReset.jsx
js/components/PasswordResetPage.jsx

This should fix the password reset.
I couldn't actually find anything wrong, except that the formatting on the input box was really messed up. I restyled that and caught some other weird things along the way

Fix password reset issue

---

api/handlers/transaction.js
api/models/Transaction.js
api/routes/TransactionRoutes.js
js/components/LoginPage.jsx
spec/transaction_handler_spec.js

Create new login page message

---

js/actions/CategoriesActionCreator.js
js/actions/RepcoinServerActionCreator.js
js/api.js
js/components/CategoriesPage.jsx
js/components/CategoriesPageFilter.jsx
js/constants/RepcoinConstants.js
js/dispatcher/RepcoinAppDispatcher.js
js/stores/CategoriesStore.js
package.json

I'm going to put comments on this to explain a bunch of stuff, but let's just plan on going over it together because I think that that will be the best way to explain it anyway.

Implement flux for the categories page

---

api/handlers/combo.js
api/handlers/transaction.js
api/models/AddExpertEvent.js
api/models/JoinEvent.js
api/models/NewCategoryEvent.js
api/models/Transaction.js
api/routes/ComboRoutes.js
api/routes/TransactionRoutes.js
js/components/Feed.jsx
js/components/FeedItem.jsx
package.json
spec/combo_handler_spec.js
spec/transaction_handler_spec.js

Build feed pagination

---

js/components/AddExpertEventFeedItem.jsx
js/components/EventFeedItem.jsx
js/components/Feed.jsx
js/components/JoinFeedItem.jsx
js/components/NewCategoryFeedItem.jsx

Fix feed bugs

---

js/actions/AuthActionCreator.js
js/actions/NotificationsActionCreator.js
js/actions/RepcoinServerActionCreator.js
js/api.js
js/components/Toolbar.jsx
js/constants/RepcoinConstants.js
js/stores/AuthStore.js
js/stores/CategoriesStore.js
js/stores/NotificationsStore.js
js/stores/__tests__/AuthStore-test.js
js/stores/__tests__/NotificationsStore-test.js

Continuing the Flux domination one component at a time.

Convert Toolbar to Flux

---

js/components/CategoriesItem.jsx
js/components/CategoriesTable.jsx

Add reps received to expert categories table

---

js/components/Modal.jsx

Replace button with pending during transaction

---

api/handlers/user.js
api/handlers/usersnapshot.js
api/models/Transaction.js
api/models/User.js
api/models/UserSnapshot.js
api/routes/UserRoutes.js
api/routes/UserSnapshotRoutes.js
css/app.css
index.ejs
js/app.jsx
js/components/Dashboard.jsx
js/components/GoogleColumnChart.jsx
js/components/GoogleLineChart.jsx
js/components/HomePage.jsx
js/components/MiniInvestButton.jsx
js/components/PanelAll.jsx
js/components/PanelExpert.jsx
js/components/PanelInvestor.jsx
js/components/UserTable.jsx
js/components/UserTableItem.jsx
server.js
spec/user_handler_spec.js
spec/user_snapshot_handler_spec.js

This is a big PR please take a look when you have a chance

Add dashboard

---

js/components/UserTableItem.jsx

Fix table categories order

---

api/handlers/user.js
api/models/User.js
js/components/InstantBox.jsx
spec/user_handler_spec.js

Speed up search bar

---

css/app.css
js/components/CategoryPage.jsx
js/components/Dashboard.jsx
js/components/HomePage.jsx
js/components/LeaderTable.jsx
js/components/MiniInvestButton.jsx
js/components/Modal.jsx
js/components/TrendingTable.jsx
js/stores/AuthStore.js

Fix mini button and add to category page

---

.gitignore
bin/removeInvestorsWithRankZero.js
bin/utils.js
spec/jobs_utils_spec.js

Remove users with investor rank zero

---

bin/utils.js
spec/jobs_utils_spec.js

Do not let dividends make a user fall below zero reps

---

api/handlers/user.js
api/models/Transaction.js
spec/user_handler_spec.js

Fix trending sort

---

api/models/User.js
api/routes/utils.js
bin/migrateRankToUsers.js
bin/utils.js

Fix rank tie

---

js/components/AddExpertEventFeedItem.jsx
js/components/Feed.jsx
js/components/ProfilePage.jsx
js/stores/AuthStore.js

This needs to get in before we push to Heroku.

Fix Feed invariant violation for public users

---

js/components/HomePage.jsx
package.json

Extraneous semicolon in HTML causes it to show on site

Remove semicolon

---

js/components/AboutBox.jsx
js/components/CategoriesTable.jsx
js/components/LinkItem.jsx
js/components/LinksBox.jsx
js/components/LocationBox.jsx
js/components/Toolbar.jsx

Changes profile page so that the prompts to update will show all the time, not just on hover.
Changes the Toolbar Profile link to say "profile"

Remove hover on profile update prompt and change toolbar profile link

---

analysis.py

Iteration 0 of data mining for tracking
